### ISSUE TITLE
Sagepay Integration Methods

### ISSUE THREAD

**Issue by madurak** [circleinteractive/uk.co.circleinteractive.payment.sagepay#16]
Hi,

This is not a issue, but just a quick question. So Sagepay uses 3 types of integration methods - Form, Server and Direct. (http://www.sagepay.co.uk/support/12/36/integrations)
Can you let me know which method this extension uses? Its probably either Form or Server where its off site payment. Can you confirm which one please?

Thanks
Madura

**Comment by andy-walker** [comment]
Hi Madura - yes, it's the Server integration method this one uses.

**Comment by madurak** [comment]
Thanks for the prompt response Andy.
