### ISSUE TITLE
White screen trying to pay using sagepay

### ISSUE THREAD

**Issue by bradydan** [circleinteractive/uk.co.circleinteractive.payment.sagepay#18]
We are getting a white screen when trying to make a payment via sagepay (eg registering on a paid event)

- CiviCRM 4.7.17 
- sagepay extension Version 3.1.0 	(Jan 12 2016)
- WordPress  4.7.3 
- PHP 5.6.30

[Here is an example event](https://ifm.org.uk/civicrm/?page=CiviCRM&q=civicrm/event/register&reset=1&id=131)

We do not have cron running on the server, though I doubt that is related

Has this extension been tested with CiviCRM 4.7.17 ?

**Comment by andy-walker** [comment]
Hi Dan - as discussed via email, I've merged the 4.7-dev into master and committed some bugfixes that were pending - so will go ahead and close this for now. But feel free to contact me or open another issue if you're still having any problems with it.
