### ISSUE TITLE
TLS v1.2 support

### ISSUE THREAD

**Issue by mattwire** [circleinteractive/uk.co.circleinteractive.payment.sagepay#22]
Currently this extension forces TLSv1.0 here: https://github.com/circleinteractive/uk.co.circleinteractive.payment.sagepay/blob/master/custom/php/CRM/Core/Payment/Sagepay.php#L511

Emails from sagepay state they will only accept TLSv1.2 from April 2018

**Comment by stuart897** [comment]
I don't think that forces TLSv1.0, according to the Curl docs it only sets a preference: https://curl.haxx.se/libcurl/c/CURLOPT_SSLVERSION.html

So when the SagePay servers reject 1.0 I believe it will switch to 1.2 (providing your own webserver supports the newer protocol).

I'm not saying the Curl parameters shouldn't be amended (CURLOPT_SSL_VERIFYPEER should also be true in my opinion) but I don't think this extension will break in April.

**Comment by mattwire** [comment]
@stuart897 Thanks, that makes sense

**Comment by davejenx** [comment]
According to https://curl.haxx.se/libcurl/c/CURLOPT_SSLVERSION.html , CURL_SSLVERSION_TLSv1 means TLSv1.x (not TLSv1.0: there's a separate constant, CURL_SSLVERSION_TLSv1_0  for that). The code example on that page uses CURL_SSLVERSION_TLSv1 with comment, "ask libcurl to use TLS version 1.0 or later". I believe the SSL negotiation should result in server and client agreeing on the newest version that they both support.

**Comment by mattwire** [comment]
@davejenx Think I might have overreacted then :-)
