### ISSUE TITLE
API update

### ISSUE THREAD

**Issue by Denitz** [circleinteractive/uk.co.circleinteractive.payment.sagepay#3]
Any plans on update to API v3.0?
Current code uses v2.23 which is unsupported since 31st July 2015.

**Comment by circleinteractive** [comment]
We are planning to get this done towards the end of this week / early next week - have just been sorting out a test environment where we can do the work.

Will update this issue to let you know when we've done that.

**Comment by circleinteractive** [comment]
That should be done and have tested that, but let us know if you come across any problems.
