### ISSUE TITLE
SagePay Webform Integratoion

### ISSUE THREAD

**Issue by rajivtanna** [circleinteractive/uk.co.circleinteractive.payment.sagepay#4]
Hi Andy,

Firstly thanks for the module - we use this for our organisation and it works great. 

We have recently tested using this with webforms and it is working great other than one issue which is to do with the redirect URL. Once the payment completes it redirects the user back to the civi contribution page but we need it return to the webform page that we are using in with the civi integration for a number of our forms. 

I am pretty sure it requires an adjustment to line 468 of the ipn.php but before we adjust I wanted to know if you had come across the issue and if not could you caste any light on if you think this is the correct place.

Regards,

Raj

**Comment by circleinteractive** [comment]
Hi Raj,

Apologies for the delay in replying - that is right though. It is the returnURL you would want to change in that case, or you could maybe set up a redirect on the Civi url in your webserver config, which might save you maintaining a customized version of the extension.

We could also maybe look into providing an input field for a custom return url on the payment processor setup form in the future though if that would make it work better with webform_civicrm.

Hope that helps anyway,

Andy
