### ISSUE TITLE
Force CURL_SSLVERSION_TLSv1

### ISSUE THREAD

**Issue by Denitz** [circleinteractive/uk.co.circleinteractive.payment.sagepay#9]
Read http://www.engage.sagepay.com/poodle

we need to add
```CURLOPT_SSLVERSION     => 1,```

for ```curl_setopt_array()``` call in sagepay.php

Missing this option can be a problem on servers with default CURL SSL version other than TLSv1.

**Comment by andy-walker** [comment]
That is fixed in the new version, which is in another branch at the moment - will merge into master shortly once we've completed testing it.
